j1866cppDisplayWeb/urls.py
from django.conf.urls import url,include
from django.contrib import admin
#from django.urls import path


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #path('admin/',admin.site.urls),
    url(r'^' ,include("mainpage.urls",namespace="mainpage")),
]

mainpage/urls.py
from django.conf.urls import url

from . import views

app_name='[mainpage]'

urlpatterns = [
    url(r'^$', views.index, name= 'index'),
    url(r'^login$', views.login, name= 'login'),
    url(r'^logon$', views.logon, name= 'logon'),
    url(r'^loginback$', views.loginback, name= 'loginback'),
    url(r'^logonback$', views.logonback, name= 'logonback'),
    url(r'^uploadfile$', views.uploadfile, name= 'uploadfile'),
    url(r'^showFiles$', views.showFiles, name= 'showFiles'),
    url(r'^download(.*)', views.download, name= 'download'),
]

mainpage/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models

# Create your models here.

# python manage.py makemigrations mainpage
# python manage.py migrate mainpage

class modelUserMsg(models.Model):  #质量要素表
    userName = models.CharField(max_length=25)   
    passWord = models.CharField(max_length = 25)

mainpage/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render_to_response

import random
import os
from  django.conf import settings
from mainpage.models import modelUserMsg  

# Create your views here.

def index(request):     #设置cookies  
    response= render_to_response('index.html') 
    #if not os.path.exists(os.path.join(settings.BASE_DIR, "username.txt")):
        #frecode= open(os.path.join(settings.BASE_DIR, "username.txt"), 'w')#记录用户名
        #frecode.close()
    if "user_cookie" not in request.COOKIES:
        strlist="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ123456789"
        usermess=''
        for i in range(20):
            usermess=usermess+strlist[random.randint(0,len(strlist)-1)]
        #print(usermess)
        response.set_cookie('user_cookie',usermess,365*24*60*60*1)#设置
        response.set_cookie('user_name',' ',365*24*60*60*1)#设置用户名
        response.set_cookie('user_passd',' ',365*24*60*60*1)#设置密码
    return response  
	
def login(request):
    return render_to_response('login.html')
def logon(request):
    return render_to_response('logon.html')
    
from django.views.decorators.csrf import csrf_exempt	#这两句是让下面的函数接受form表单的上传文件不会出CSRF的错误，在html 的form中加一句 {% csrf_token %}

@csrf_exempt
def logonback(request):  #注册
    uname=request.POST['username']
    pword=request.POST['password']   
    if 'logon' in request.POST:     #注册 ,logon为input中的name属性
        if len(uname)<4 or len(pword)<4 :
            context={
                'errormessage':"用户名或密码长度不能小于等于4！",
                }
            return render_to_response('logon.html',context)
   
        if modelUserMsg.objects.filter(userName=uname).count()>0:
            context={
            'errormessage':"用户名已注册！",
            }
            response= render_to_response('logon.html',context) 
            return response #注册失败
        
        #注册成功
        pro=modelUserMsg.objects.create(#存入数据库
			userName = uname,
			passWord = pword,
		)
        pro.save()
        
        context={
        'errormessage':"注册成功请在登录客户端登录！",
        }
        response= render_to_response('logon.html',context) 
        return response 
        
        response= render_to_response('login.html')
        return response
    if 'delete' in request.POST:     #注销
        if len(uname)<1 or len(pword)<1 :
            context={
                'errormessage':"请正确输入要注销的账户名和密码",
                }
            return render_to_response('logon.html',context)

        modelUserMsg.objects.filter(userName=uname).delete()#删除
        context={
        'errormessage':"操作完成",
        }
        response= render_to_response('logon.html',context) 
        return response 
    
@csrf_exempt
def loginback(request):     #登录
    uName=request.POST['username']
    pWord=request.POST['password']
    if len(uName)<1 or len(pWord)<1 :
        return render_to_response('login.html')
    umess = modelUserMsg.objects.filter(userName=uName).values_list("passWord")
    for data in umess:
        if  pWord==data[0]:
            #return HttpResponse("helloworld")
            context=dict(
                fname=getFilesName(request.POST["username"]),
                uname=uName,
                pword=pWord,
            )
            response= render_to_response('loginback.html',context) 
            response.set_cookie('user_name',uName,24*60*60)#设置用户名,1天
            response.set_cookie('user_passd',pWord,24*60*60)#设置密码
            #return HttpResponse("helloworld")
            return response #登录成功
    
    #登录失败 
    context={
    'errormessage':"用户名或密码错误请重新输入！",
    }
    response= render_to_response('login.html',context)
    return response
    
def showFiles(request):
    context=dict(
        fname=getFilesName(request.COOKIES["user_name"]),
        uname=request.COOKIES["user_name"],
        pword=request.COOKIES["user_passd"],
    )
    response= render_to_response('loginback.html',context) 
    return response
    
@csrf_exempt	
def uploadfile(request):
    if request.method == 'POST':# 获取对象
        obj = request.FILES.get('File')
        # 上传文件的文件名
        #print(obj.name)
        ucname = request.COOKIES["user_name"]
        uploaddir = os.path.join(settings.BASE_DIR, "uploadFiles")
        if  os.path.exists(os.path.join(uploaddir,ucname)):	#新建上传项目路径
            pass
        else:
            os.mkdir(os.path.join(uploaddir,ucname))

        uploaddir=os.path.join(uploaddir,ucname)		#整合之后的文件	
        #print(uploaddir+ucookie)
        fileNameb=os.path.join(uploaddir, obj.name)
        print(fileNameb)
        fupload = open(fileNameb, 'wb')
        for chunk in obj.chunks():
            fupload.write(chunk)	#保存文件
        fupload.close()
    
    context=dict(
        fname=getFilesName(ucname),
        uname=request.COOKIES["user_name"],
        pword=request.COOKIES["user_passd"],
    )
    response= render_to_response('loginback.html',context) 
   # for i in getFilesName(ucname):
        #print(i)
    return response


   
def getFilesName(uname):
    filesName=[]
    uploaddir = os.path.join(settings.BASE_DIR, "uploadFiles")
    uploaddir=os.path.join(uploaddir,uname)		
    for parent,dirs,files in os.walk(uploaddir):
        for filename in files:
            filesName.append(filename)
    return filesName


def download(request,fileName):
    file = open(os.path.join(settings.BASE_DIR, "uploadFiles",request.COOKIES["user_name"],fileName), 'rb')
    response = HttpResponse(file)
    response['Content-Type'] = 'application/octet-stream' #设置头信息，告诉浏览器这是个文件
    response['Content-Disposition'] = 'attachment;filename='+fileName
    return response

mainpage/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    {% load staticfiles %}

    <title>初始化</title>

</head>

<body>
<span class="logo"> </span>
<br><br><br><br>
    <div id="nav_bar"></div>
    <div id="footer"></div>

<script>

window.location.href="{% url 'mainpage:login' %}";
</script>
</body>

</html>





 

mainpage/templates/login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

 {% load staticfiles %} 
 <meta charset= "utf-8">
<title>登录</title>

<link href="{% static 'css/index.css' %}" rel="stylesheet" type="text/css" />
<script src="{% static 'js/index.js' %}"></script>

<style>
    body{
        margin:0px;
        padding:0px;
        background: url("{% static 'images/1.jpg' %}") ;  
        background-repeat : no-repeat  ; 
        
        background-size:100%;  
        
    }
    a { 
    text-decoration:none;
    }
</style>

</head>

<body>

<center>
    <table >
        <form name="frm" action="{% url 'mainpage:loginback' %}" method="post"  title="登陆" enctype="multipart/form-data">	
        {% csrf_token %}
	        <tr height="50px">
		        <th colspan=2><label for="user" accesskey="u">登陆</label></th>
			<br><br>
			
	        </tr>	
	        <tr height="50px">
		        <th><label for="user" accesskey="u">用户名</label></th>
		        <td>
			        <input id="user" type="text" name="username" size="25" maxlength="20" value=""><!--最大长度10--> 
		        </td>	
	        </tr>	

	        <tr height="50px">
		        <th>密码</th>
		        <td>
			        <input type="password" name="password" size="25" maxlength="20" value="">
		        </td>	
	        </tr>	
	        <tr height="50px">
		        <th></th>
		        <td>
			        <input type="submit" name="login" style="margin:0px 30% 0px 0px ;" value="登陆">
   
                   <a href="{% url 'mainpage:logon' %}" >账户管理</a>
                </td>
		        </td>	
	        </tr>
        </form>	
               
			
    </table>
    <br>
    {{errormessage}}
</center>

</body>
</html>

mainpage/templates/loginback.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

 {% load staticfiles %}
<title>文件管理</title>

<style>
    body{
        background: url("{% static 'images/main.jpg' %}") ;  
        background-repeat : no-repeat  ;
        margin:0px;
        padding:0px;
        
    }
    #uname{
       position:absolute ;right:5px; top:5px;
       border-style:double    ;
       border-color:#889;

    }
    #files{
        border-style:outset ;
        position:absolute ;right:2%; top:10%;
        overflow:auto;
        height:70%;
        width:60%;
    }
    #edit{
        border-style:outset ;
        position:absolute ;left:2%; top:10%;
        background :#eef;
        filter:alpha(opacity=60);-moz-opacity:0.6;opacity:0.60;
        height:70%;
        width:30%;
    }
    #edit-textarea{
        background :#eef;
        filter:alpha(opacity=60);-moz-opacity:0.6;opacity:0.60;
    }
    .jihuo{
        position:absolute ;bottom:4%; left:5%;
       border-style:outset ;
       border-width : thin ;
       border-color :#ddf;
        height:30px;
        width:50px;
        text-align :center;
        margin:0px;
        padding:0px;
        background-color:rgba(255,255,255,0.5);
    }
   
    .refrsh{
        position:absolute ;bottom:4%; left:50%;
       border-style:outset ;
       border-width : thin ;
       border-color :#ddf;
        height:30px;
        width:50px;
        text-align :center;
        margin:0px;
        padding:0px;
        background-color:rgba(255,255,255,0.5);
    }
     .upload{
        position:absolute ;bottom:4%; right:20%;
       
        text-align :center;
        margin:0px;
        padding:0px;
    }
    .uploadbutton{
        border-style:outset ;
        border-width : thin ;
        border-color :#ddf;
        height:30px;
        width:50px;
        text-align :center;
        margin:0px;
        padding:0px;
        background-color:rgba(255,255,255,0.5);

    }
     .download{
     
        position:absolute ;bottom:4%; right:5%;
       border-style:outset ;
       border-width : thin ;
       border-color :#ddf;
       height:30px;
        width:50px;
        text-align :center;
        margin:0px;
        padding:0px;
        background-color:rgba(255,255,255,0.5);
    }
    .file{
      
        padding:2px 0px 2px 5px;
        border-style:double ;
    }
    
</style>

<script src="{% static 'js/upload.js' %}"></script>
</head>

<body>

    <div id="uname">
       用户 <span style="border-style:double;border-color:#889;color:#ddf;margin:0px;">{{uname}}</span>你好
    </div>
    <div id="files">
        <script>
     
            {% for j in fname %}        
               
               var filestyle="<div class='file' >\
               <input type='checkbox' name='item' value='{{j}}' />{{j}}\
               </div>"
                document.writeln(filestyle);

            {% endfor %}  

        </script>
    </div>

        <textarea id="edit">此处编辑</textarea>

    <div>
        <a class="jihuo" onclick="relive(this);">激活</a>
        <a class="refrsh" onclick="refresh(this);">刷新</a>
     <!--   <div class="upload">
            <form class=notice action="{% url 'mainpage:uploadfile' %}" method="post" enctype="multipart/form-data" style="margin:0px ;padding: 0px; " id="test_form">
            {% csrf_token %}

            <input type="file" style="margin:0px ;padding: 0px;" id="up_file" name="File" />                   
            <input id="submit_upload" class="uploadbutton" type="button"  value="上传"  onclick="fileChange(this);"/>   
            </form>
        </div> -->
        <a class="download" onclick="Download(this);">下载</a>
    </div>

</body>
</html>

mainpage/templates/logon.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

 {% load staticfiles %}
<title>帐号管理</title>

<link href="{% static 'css/index.css' %}" rel="stylesheet" type="text/css" />
<script src="{% static 'js/index.js' %}"></script>

<style>
    body{
        background: url("{% static 'images/1.jpg' %}");   
        background-repeat : no-repeat  ;  
        margin:0px;
        padding:0px;
        background-size:100%;  
    }
  
</style>

</head>

<body>

<center>
    <table >
        <form name="frm" action="logonback" method="post"  title="注册" enctype="multipart/form-data">	
        {% csrf_token %}
	        <tr height="50px">
		        <th colspan=2><label for="user" accesskey="u">帐号管理</label></th>
			<br><br>
			
	        </tr>	
	        <tr height="50px">
		        <th><label for="user" accesskey="u">用户名</label></th>
		        <td>
			        <input id="user" type="text" name="username" size="25" maxlength="20" value=""><!--最大长度10--> 
		        </td>	
	        </tr>	

	        <tr height="50px">
		        <th>密码</th>
		        <td>
			        <input type="password" name="password" size="25" maxlength="20" value="">
		        </td>	
	        </tr>	
	        <tr height="50px" >
		        <th></th>
		        <td>
			        <input type="submit"  name="logon" style="margin:0px 40% 0px 0px;" value="注册">
			        <input type="submit"  name="delete"  value="注销">
		        </td>	
	        </tr>
        </form>	
    </table>
    <br>
    {{errormessage}}
</center>

</body>
</html>